create table public.generation_traces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  learning_request_id uuid not null references public.learning_requests (id) on delete cascade,
  course_id uuid references public.courses (id) on delete set null,
  stage text not null,
  target text not null,
  prompt_version text not null,
  schema_version text not null,
  model text not null,
  attempt int not null,
  started_at timestamptz not null,
  duration_ms int not null,
  input_tokens int not null default 0,
  output_tokens int not null default 0,
  reasoning_tokens int not null default 0,
  total_tokens int not null default 0,
  status text not null,
  validation_codes text[] not null default '{}',
  qa_result text,
  web_search boolean not null default false,
  created_at timestamptz not null default now(),
  constraint generation_traces_status_check check (status in ('ok', 'invalid', 'failed'))
);
